GET http://localhost:3000/api/courses HTTP/1.1

###

POST http://localhost:3000/api/courses HTTP/1.1
content-type: application/json

{
  "name": "post course"
}

###

PUT http://localhost:3000/api/courses/1 HTTP/1.1
content-type: application/json

{
  "name": "put course"
}

###

DELETE http://localhost:3000/api/courses/1 HTTP/1.1